package zairus.hermitron.item;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import zairus.hermitron.item.ItemHermitron.Rarity;
import zairus.hermitron.item.ItemHermitron.Version;

public class HTItems
{
	public static final ItemBase A0C_DIOTREE;
	public static final ItemBase A0C_OAKAN;
	public static final ItemBase A0C_TAIGA;
	public static final ItemBase A0M_FERNOA;
	public static final ItemBase A0R_GRASSU;
	public static final ItemBase A0R_LILLY;
	public static final ItemBase A0U_CACTI;
	public static final ItemBase A0U_FOLIA;
	public static final ItemBase A0U_PRICLE;
	public static final ItemBase A0_COMPLETED_SET;
	public static final ItemBase A1C_AMY;
	public static final ItemBase A1C_CRYSTAL;
	public static final ItemBase A1C_FLUORA;
	public static final ItemBase A1M_DIANNA;
	public static final ItemBase A1R_RUBRA;
	public static final ItemBase A1R_SAPPHI;
	public static final ItemBase A1U_AQUA;
	public static final ItemBase A1U_EMMA;
	public static final ItemBase A1U_TORY;
	public static final ItemBase A1_COMPLETED_SET;
	public static final ItemBase A2C_CHORY;
	public static final ItemBase A2C_SPACEROCK;
	public static final ItemBase A2C_TELE;
	public static final ItemBase A2M_DRAGONBORNE;
	public static final ItemBase A2R_BOXES;
	public static final ItemBase A2R_ELYTRON;
	public static final ItemBase A2U_CRYSTAN;
	public static final ItemBase A2U_OPTICA;
	public static final ItemBase A2U_POPCHORN;
	public static final ItemBase A2_COMPLETED_SET;
	public static final ItemBase A3C_HELLROCK;
	public static final ItemBase A3C_INFERNO;
	public static final ItemBase A3C_PHOSPHOR;
	public static final ItemBase A3M_SIDERIS;
	public static final ItemBase A3R_CRACKLES;
	public static final ItemBase A3R_DEATHBONE;
	public static final ItemBase A3U_BURNS;
	public static final ItemBase A3U_MORB;
	public static final ItemBase A3U_QUZAT;
	public static final ItemBase A3_COMPLETED_SET;
	public static final ItemBase A4C_NEMES;
	public static final ItemBase A4C_SAM;
	public static final ItemBase A4C_SQUIDDLY;
	public static final ItemBase A4M_ENROTH;
	public static final ItemBase A4R_LANTAN;
	public static final ItemBase A4R_THORNE;
	public static final ItemBase A4U_CATCHER;
	public static final ItemBase A4U_PRISMARU;
	public static final ItemBase A4U_SCALES;
	public static final ItemBase A4_COMPLETED_SET;
	public static final ItemBase A5C_DAISY;
	public static final ItemBase A5C_LYON;
	public static final ItemBase A5C_POPPERS;
	public static final ItemBase A5M_ORCHALCUM;
	public static final ItemBase A5R_ALLIE;
	public static final ItemBase A5R_TULA;
	public static final ItemBase A5U_AZURI;
	public static final ItemBase A5U_RHODOS;
	public static final ItemBase A5U_SOL;
	public static final ItemBase A5_COMPLETED_SET;
	public static final ItemBase A6C_DRIPPLE;
	public static final ItemBase A6C_PUFF;
	public static final ItemBase A6C_WISPS;
	public static final ItemBase A6M_BOLT;
	public static final ItemBase A6R_ASTER;
	public static final ItemBase A6R_LUNA;
	public static final ItemBase A6U_HELIO;
	public static final ItemBase A6U_RAVEN;
	public static final ItemBase A6U_WHOOSH;
	public static final ItemBase A6_COMPLETED_SET;
	public static final ItemBase A7C_BREW;
	public static final ItemBase A7C_EXPER;
	public static final ItemBase A7C_HOPPS;
	public static final ItemBase A7R_PHEONIX;
	public static final ItemBase A7U_CARRI;
	public static final ItemBase A7R_DRACHIS;
	public static final ItemBase A7M_ERIS;
	public static final ItemBase A7U_SPECTRUM;
	public static final ItemBase A7U_TERRY;
	public static final ItemBase A7_COMPLETED_SET;
	public static final ItemBase A8C_RAWSHACH;
	public static final ItemBase A8C_ROASTER;
	public static final ItemBase A8C_SACCHAH;
	public static final ItemBase A8R_COOOKIEYS;
	public static final ItemBase A8M_LYRA;
	public static final ItemBase A8R_SHREW;
	public static final ItemBase A8U_DOH;
	public static final ItemBase A8U_GRILL;
	public static final ItemBase A8U_ROUTE;
	public static final ItemBase A8_COMPLETED_SET;
	public static final ItemBase A9C_SKELETON;
	public static final ItemBase A9C_SLIME;
	public static final ItemBase A9C_ZOMBIE;
	public static final ItemBase A9M_RENDOG;
	public static final ItemBase A9R_ENDERMAN;
	public static final ItemBase A9R_WITHERSKELETON;
	public static final ItemBase A9U_CREEPER;
	public static final ItemBase A9U_MAGMACUBE;
	public static final ItemBase A9U_SPIDER;
	public static final ItemBase A9_COMPLETED_SET;
	
	public static Map<Version, List<ItemHermitron>> hermitron_sets = new HashMap<Version, List<ItemHermitron>>();
	public static List<ItemHermitronSet> hermitron_complete_sets = new ArrayList<ItemHermitronSet>();
	
	static
	{
		hermitron_sets.put(Version.ALPHA, new ArrayList<ItemHermitron>());
		hermitron_sets.put(Version.BETA, new ArrayList<ItemHermitron>());
		hermitron_sets.put(Version.GAMA, new ArrayList<ItemHermitron>());
		
		A0C_DIOTREE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.COMMON).setItemName("a0c_diotree");
		A0C_OAKAN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.COMMON).setItemName("a0c_oakan");
		A0C_TAIGA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.COMMON).setItemName("a0c_taiga");
		A0M_FERNOA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.MYTHIC).setItemName("a0m_fernoa");
		A0R_GRASSU = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.RARE).setItemName("a0r_grassu");
		A0R_LILLY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.RARE).setItemName("a0r_lilly");
		A0U_CACTI = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.UNCOMMON).setItemName("a0u_cacti");
		A0U_FOLIA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.UNCOMMON).setItemName("a0u_folia");
		A0U_PRICLE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(0).setRarity(Rarity.UNCOMMON).setItemName("a0u_pricle");
		A0_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(0).setItemName("a0_completed_set");
		A1C_AMY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.COMMON).setItemName("a1c_amy");
		A1C_CRYSTAL = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.COMMON).setItemName("a1c_crystal");
		A1C_FLUORA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.COMMON).setItemName("a1c_fluora");
		A1M_DIANNA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.MYTHIC).setItemName("a1m_dianna");
		A1R_RUBRA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.RARE).setItemName("a1r_rubra");
		A1R_SAPPHI = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.RARE).setItemName("a1r_sapphi");
		A1U_AQUA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.UNCOMMON).setItemName("a1u_aqua");
		A1U_EMMA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.UNCOMMON).setItemName("a1u_emma");
		A1U_TORY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(1).setRarity(Rarity.UNCOMMON).setItemName("a1u_tory");
		A1_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(1).setItemName("a1_completed_set");
		A2C_CHORY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.COMMON).setItemName("a2c_chory");
		A2C_SPACEROCK = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.COMMON).setItemName("a2c_spacerock");
		A2C_TELE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.COMMON).setItemName("a2c_tele");
		A2M_DRAGONBORNE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.MYTHIC).setItemName("a2m_dragonborne");
		A2R_BOXES = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.RARE).setItemName("a2r_boxes");
		A2R_ELYTRON = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.RARE).setItemName("a2r_elytron");
		A2U_CRYSTAN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.UNCOMMON).setItemName("a2u_crystan");
		A2U_OPTICA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.UNCOMMON).setItemName("a2u_optica");
		A2U_POPCHORN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(2).setRarity(Rarity.UNCOMMON).setItemName("a2u_popchorn");
		A2_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(2).setItemName("a2_completed_set");
		A3C_HELLROCK = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.COMMON).setItemName("a3c_hellrock");
		A3C_INFERNO = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.COMMON).setItemName("a3c_inferno");
		A3C_PHOSPHOR = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.COMMON).setItemName("a3c_phosphor");
		A3M_SIDERIS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.MYTHIC).setItemName("a3m_sideris");
		A3R_CRACKLES = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.RARE).setItemName("a3r_crackles");
		A3R_DEATHBONE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.RARE).setItemName("a3r_deathbone");
		A3U_BURNS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.UNCOMMON).setItemName("a3u_burns");
		A3U_MORB = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.UNCOMMON).setItemName("a3u_morb");
		A3U_QUZAT = new ItemHermitron().setVersion(Version.ALPHA).setTribe(3).setRarity(Rarity.UNCOMMON).setItemName("a3u_quzat");
		A3_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(3).setItemName("a3_completed_set");
		A4C_NEMES = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.COMMON).setItemName("a4c_nemes");
		A4C_SAM = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.COMMON).setItemName("a4c_sam");
		A4C_SQUIDDLY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.COMMON).setItemName("a4c_squiddly");
		A4M_ENROTH = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.MYTHIC).setItemName("a4m_enroth");
		A4R_LANTAN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.RARE).setItemName("a4r_lantan");
		A4R_THORNE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.RARE).setItemName("a4r_thorne");
		A4U_CATCHER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.UNCOMMON).setItemName("a4u_catcher");
		A4U_PRISMARU = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.UNCOMMON).setItemName("a4u_prismaru");
		A4U_SCALES = new ItemHermitron().setVersion(Version.ALPHA).setTribe(4).setRarity(Rarity.UNCOMMON).setItemName("a4u_scales");
		A4_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(4).setItemName("a4_completed_set");
		A5C_DAISY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.COMMON).setItemName("a5c_daisy");
		A5C_LYON = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.COMMON).setItemName("a5c_lyon");
		A5C_POPPERS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.COMMON).setItemName("a5c_poppers");
		A5M_ORCHALCUM = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.MYTHIC).setItemName("a5m_orchalcum");
		A5R_ALLIE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.RARE).setItemName("a5r_allie");
		A5R_TULA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.RARE).setItemName("a5r_tula");
		A5U_AZURI = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.UNCOMMON).setItemName("a5u_azuri");
		A5U_RHODOS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.UNCOMMON).setItemName("a5u_rhodos");
		A5U_SOL = new ItemHermitron().setVersion(Version.ALPHA).setTribe(5).setRarity(Rarity.UNCOMMON).setItemName("a5u_sol");
		A5_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(5).setItemName("a5_completed_set");
		A6C_DRIPPLE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.COMMON).setItemName("a6c_dripple");
		A6C_PUFF = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.COMMON).setItemName("a6c_puff");
		A6C_WISPS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.COMMON).setItemName("a6c_wisps");
		A6M_BOLT = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.MYTHIC).setItemName("a6m_bolt");
		A6R_ASTER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.RARE).setItemName("a6r_aster");
		A6R_LUNA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.RARE).setItemName("a6r_luna");
		A6U_HELIO = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.UNCOMMON).setItemName("a6u_helio");
		A6U_RAVEN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.UNCOMMON).setItemName("a6u_raven");
		A6U_WHOOSH = new ItemHermitron().setVersion(Version.ALPHA).setTribe(6).setRarity(Rarity.UNCOMMON).setItemName("a6u_whoosh");
		A6_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(6).setItemName("a6_completed_set");
		A7C_BREW = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.COMMON).setItemName("a7c_brew");
		A7C_EXPER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.COMMON).setItemName("a7c_exper");
		A7C_HOPPS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.COMMON).setItemName("a7c_hopps");
		A7R_PHEONIX = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.RARE).setItemName("a7r_pheonix");
		A7U_CARRI = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.UNCOMMON).setItemName("a7u_carri");
		A7R_DRACHIS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.RARE).setItemName("a7r_drachis");
		A7M_ERIS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.MYTHIC).setItemName("a7m_eris");
		A7U_SPECTRUM = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.UNCOMMON).setItemName("a7u_spectrum");
		A7U_TERRY = new ItemHermitron().setVersion(Version.ALPHA).setTribe(7).setRarity(Rarity.UNCOMMON).setItemName("a7u_terry");
		A7_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(7).setItemName("a7_completed_set");
		A8C_RAWSHACH = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.COMMON).setItemName("a8c_rawshach");
		A8C_ROASTER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.COMMON).setItemName("a8c_roaster");
		A8C_SACCHAH = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.COMMON).setItemName("a8c_sacchah");
		A8R_COOOKIEYS = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.RARE).setItemName("a8r_coookieys");
		A8M_LYRA = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.MYTHIC).setItemName("a8m_lyra");
		A8R_SHREW = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.RARE).setItemName("a8r_shrew");
		A8U_DOH = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.UNCOMMON).setItemName("a8u_doh");
		A8U_GRILL = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.UNCOMMON).setItemName("a8u_grill");
		A8U_ROUTE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(8).setRarity(Rarity.UNCOMMON).setItemName("a8u_route");
		A8_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(8).setItemName("a8_completed_set");
		A9C_SKELETON = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.COMMON).setItemName("a9c_skeleton");
		A9C_SLIME = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.COMMON).setItemName("a9c_slime");
		A9C_ZOMBIE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.COMMON).setItemName("a9c_zombie");
		A9M_RENDOG = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.MYTHIC).setItemName("a9m_rendog");
		A9R_ENDERMAN = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.RARE).setItemName("a9r_enderman");
		A9R_WITHERSKELETON = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.RARE).setItemName("a9r_witherskeleton");
		A9U_CREEPER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.UNCOMMON).setItemName("a9u_creeper");
		A9U_MAGMACUBE = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.UNCOMMON).setItemName("a9u_magmacube");
		A9U_SPIDER = new ItemHermitron().setVersion(Version.ALPHA).setTribe(9).setRarity(Rarity.UNCOMMON).setItemName("a9u_spider");
		A9_COMPLETED_SET = new ItemHermitronSet().setVersion(Version.ALPHA).setTribe(9).setItemName("a9_completed_set");
	}
	
	public static final void register()
	{
		A0C_DIOTREE.register();
		A0C_OAKAN.register();
		A0C_TAIGA.register();
		A0M_FERNOA.register();
		A0R_GRASSU.register();
		A0R_LILLY.register();
		A0U_CACTI.register();
		A0U_FOLIA.register();
		A0U_PRICLE.register();
		A0_COMPLETED_SET.register();
		A1C_AMY.register();
		A1C_CRYSTAL.register();
		A1C_FLUORA.register();
		A1M_DIANNA.register();
		A1R_RUBRA.register();
		A1R_SAPPHI.register();
		A1U_AQUA.register();
		A1U_EMMA.register();
		A1U_TORY.register();
		A1_COMPLETED_SET.register();
		A2C_CHORY.register();
		A2C_SPACEROCK.register();
		A2C_TELE.register();
		A2M_DRAGONBORNE.register();
		A2R_BOXES.register();
		A2R_ELYTRON.register();
		A2U_CRYSTAN.register();
		A2U_OPTICA.register();
		A2U_POPCHORN.register();
		A2_COMPLETED_SET.register();
		A3C_HELLROCK.register();
		A3C_INFERNO.register();
		A3C_PHOSPHOR.register();
		A3M_SIDERIS.register();
		A3R_CRACKLES.register();
		A3R_DEATHBONE.register();
		A3U_BURNS.register();
		A3U_MORB.register();
		A3U_QUZAT.register();
		A3_COMPLETED_SET.register();
		A4C_NEMES.register();
		A4C_SAM.register();
		A4C_SQUIDDLY.register();
		A4M_ENROTH.register();
		A4R_LANTAN.register();
		A4R_THORNE.register();
		A4U_CATCHER.register();
		A4U_PRISMARU.register();
		A4U_SCALES.register();
		A4_COMPLETED_SET.register();
		A5C_DAISY.register();
		A5C_LYON.register();
		A5C_POPPERS.register();
		A5M_ORCHALCUM.register();
		A5R_ALLIE.register();
		A5R_TULA.register();
		A5U_AZURI.register();
		A5U_RHODOS.register();
		A5U_SOL.register();
		A5_COMPLETED_SET.register();
		A6C_DRIPPLE.register();
		A6C_PUFF.register();
		A6C_WISPS.register();
		A6M_BOLT.register();
		A6R_ASTER.register();
		A6R_LUNA.register();
		A6U_HELIO.register();
		A6U_RAVEN.register();
		A6U_WHOOSH.register();
		A6_COMPLETED_SET.register();
		A7C_BREW.register();
		A7C_EXPER.register();
		A7C_HOPPS.register();
		A7R_PHEONIX.register();
		A7U_CARRI.register();
		A7R_DRACHIS.register();
		A7M_ERIS.register();
		A7U_SPECTRUM.register();
		A7U_TERRY.register();
		A7_COMPLETED_SET.register();
		A8C_RAWSHACH.register();
		A8C_ROASTER.register();
		A8C_SACCHAH.register();
		A8R_COOOKIEYS.register();
		A8M_LYRA.register();
		A8R_SHREW.register();
		A8U_DOH.register();
		A8U_GRILL.register();
		A8U_ROUTE.register();
		A8_COMPLETED_SET.register();
		A9C_SKELETON.register();
		A9C_SLIME.register();
		A9C_ZOMBIE.register();
		A9M_RENDOG.register();
		A9R_ENDERMAN.register();
		A9R_WITHERSKELETON.register();
		A9U_CREEPER.register();
		A9U_MAGMACUBE.register();
		A9U_SPIDER.register();
		A9_COMPLETED_SET.register();
	}
}
